server:
  port: 8083

spring:
  application:
    name: payment
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8091/realms/microservice}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8091/realms/microservice/protocol/openid-connect/certs}

  datasource:
    url: jdbc:postgresql://localhost:5434/payment_db
    username: payment_user
    password: payment_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        enable.idempotence: true
        spring.json.type.mapping: "OrderCreated:com.service.common.events.OrderCreatedPayload,PaymentCompleted:com.service.common.events.PaymentCompletedPayload,PaymentFailed:com.service.common.events.PaymentFailedPayload"

    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.service.common.events.EventEnvelope
        spring.json.use.type.info.headers: true
        spring.json.type.mapping: "OrderCreated:com.service.common.events.OrderCreatedPayload,PaymentCompleted:com.service.common.events.PaymentCompletedPayload,PaymentFailed:com.service.common.events.PaymentFailedPayload"

    listener:
      ack-mode: manual

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
